//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string CIN { get; set; }
        public int age { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
