//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vol
    {
        public string id { get; set; }
        public int nombre_max { get; set; }
        public string destination { get; set; }
        public string ville_depart { get; set; }
        public System.DateTime date_depart { get; set; }
        public decimal prix { get; set; }
        public string compagnie { get; set; }
    }
}
